### ISSUE TITLE
Add ESS raw variables into dataset

### ISSUE THREAD

**Issue by yzhang104** [nsrr/bestair-data-dictionary#136]

**Comment by yzhang104** [comment]
ess9: while driving is missing.

**Comment by mrueschman** [comment]
Do you think it's useful? For BestAIR the driving question only exists in a raw dataset and was never pulled through the analysis pipeline into the final analytic file that we use as source data for NSRR.

**Comment by yzhang104** [comment]
I am trying to make the meta-table as complete as possible. Maybe I will just add the variable name (I assume it's ess9?) for now. THX!
