### ISSUE TITLE
Add WHIIRS raw variables into dataset

### ISSUE THREAD

**Issue by yzhang104** [nsrr/bestair-data-dictionary#137]

**Comment by yzhang104** [comment]
could you also add WHIIS survey item e: "Did you take sleeping pills to help you sleep?"

**Comment by mrueschman** [comment]
I sort of see this in the same way as #136 and "ess9". This is not a WHIIRS question, but for whatever reason was sandwiched in between the other WHIIRS questions. I can add the variable, but I probably wouldn't put it in the WHIIRS folder (i.e. https://sleepdata.org/datasets/bestair/variables?folder=Questionnaires%2FWomen%27s+Health+Initiative+Insomnia+Rating+Scale+%28WHIIRS%29) so as to avoid WHIIRS-computation confusion. Thoughts?

**Comment by yzhang104** [comment]
I agree. It is more of a "medical history" or generic sleep survey item. Similar variables are usually put under sleep questionnaire: 
slea8(hchs), tookpills(heartbeat),slpngpills5 (mesa), tkpill02 (shhs)
